spring:
  application:
    name: springboot-init
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session dead time
  session:
    timeout: 86400
    store-type: none
server:
  port: 8123
  servlet:
    context-path: /api




